# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TestSqliteToReplaceContento' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestSqliteToReplaceContento
pod 'IQKeyboardManager'
#pod 'PPRevealSideViewController', '~> 1.2.1'
pod 'AFNetworking', '~> 2.6.1'
#pod 'AMRatingControl'
pod 'MBProgressHUD'
pod 'iOS-Slide-Menu'
pod 'APParallaxHeader'
pod 'libwebp'
pod 'youtube-ios-player-helper', '~> 0.1.4'
pod 'JCNotificationBannerPresenter'

end
